name: Build Python App for Windows, Mac and Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Application for macOS
        run: |
          echo "Building macOS application..."
          pyinstaller --onefile --windowed --icon=your-icon.ico main.py

      - name: Install create-dmg on macOS
        run: |
          echo "Installing create-dmg..."
          brew install create-dmg

      - name: Create .dmg for macOS
        run: |
          echo "Creating .dmg file..."
          create-dmg dist/main.app dist/main.dmg

      - name: Archive macOS Artifacts
        run: |
          mkdir -p build_artifacts
          mv dist/main.app build_artifacts/macos-main.app
          mv dist/main.dmg build_artifacts/macos-main.dmg

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build-artifacts-${{ github.run_id }}
          path: build_artifacts/

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Application for Windows
        run: |
          pyinstaller --onefile main.py

      - name: Archive Windows Artifacts
        run: |
          mkdir -p build_artifacts
          mv dist/main.exe build_artifacts/windows-main.exe

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-artifacts-${{ github.run_id }}
          path: build_artifacts/

  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Application for Linux
        run: |
          pyinstaller --onefile main.py

      - name: Archive Linux Artifacts
        run: |
          mkdir -p build_artifacts
          mv dist/main build_artifacts/linux-main

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-build-artifacts-${{ github.run_id }}
          path: build_artifacts/
